aca_shop_homepage:
    path:     /
    defaults: { _controller: AcaShopBundle:Default:index }

aca_login_route:
    path: /login_form
    defaults: { _controller: AcaShopBundle:Login:loginForm }
    methods: [GET, POST]

aca_logout_route:
    path: /logout
    defaults: { _controller: AcaShopBundle:Login:logout }
    methods: [POST]