aca_shop_homepage:
    path:     /
    defaults: { _controller: AcaShopBundle:Default:index }

aca_login_route:
    path: /login_form
    defaults: { _controller: AcaShopBundle:Login:loginForm }
    methods: [GET, POST]

aca_logout_route:
    path: /logout
    defaults: { _controller: AcaShopBundle:Login:logout }
    methods: [POST]

aca_products:
    path: /products
    defaults: { _controller: AcaShopBundle:Product:showAll }
    methods: [GET]

aca_product_detail:
    path: /products/detail/{slug}
    defaults: { _controller: AcaShopBundle:Product:showOne }
    methods: [GET]

aca_cart:
    path: /cart
    defaults: { _controller: AcaShopBundle:Cart:showCart }
    methods: [GET]

aca_cart_add:
    path: /cart
    defaults: { _controller: AcaShopBundle:Cart:addCart }
    methods: [POST]