services:
#    aca_shop.example:
#        class: Aca\Bundle\ShopBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

   acadb:
      class: Simplon\Mysql\Mysql
      arguments: [%database_host%, %database_user%, %database_password%, %database_name%]